name: Continuous Deployment

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: [ '3.0.100' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/v}
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet pack src/Redbox.Serilog.Stackdriver --output nupkgs -p:Version=${{ steps.get_version.outputs.VERSION }}
      - run: dotnet nuget push nupkgs/Redbox.Serilog.Stackdriver.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}