name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - '' # Run on push when tag is empty
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: [ '3.0.100' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build