name: Continuous Deployment

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*' # Run on push when tag is new version, e.g. v1.1.1

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: [ '3.0.100' ]
    name: Dotnet ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF##*/v}
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet pack src/Redbox.Serilog.Stackdriver --output nupkgs -p:Version=${{ steps.get_version.outputs.VERSION }}
      - run: dotnet nuget push nupkgs/Redbox.Serilog.Stackdriver.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json